FROM luongnguyen/oyente

RUN npm install -g ganache-cli

RUN npm install -g truffle

# we use the oyente image as a base because it has a lot of dependencies
# it also comes with nodejs and npm already
# we then simply install testrpc and truffle on top
