branches:
  only:
  - master

language: node_js

node_js:
  - "lts/*"

services:
  - docker

script: bash scripts/build.sh

after_script:
  - docker images

before_deploy:
#  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- echo "Images are currently not automatically deployed to Docker Hub, please build locally!"
deploy:
  provider: script
  skip_cleanup: true
  script: bash scripts/deploy.sh
