branches:
  only:
  - master

language: node_js

node_js:
  - "lts/*"

services:
  - docker

script: bash scripts/build.sh

after_script:
  - docker images

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
  provider: script
  skip_cleanup: true
  script: bash scripts/deploy.sh
