version: "3"

services:
  authority0:
    image: maibornwolff/eden:parity-authority0
    hostname: authority0
    container_name: authority0
    build:
      context: .
      dockerfile: ./authority.Dockerfile
      args:
        PARITY_VERSION: ${PARITY_VERSION}
        NETWORK_NAME: ${NETWORK_NAME}
        ID: 0
    volumes:
      - authority0_volume:/home/parity/.local/share/io.parity.ethereum/chains/${NETWORK_NAME}/db
    command: --config /parity/config/authority.toml
      --engine-signer 0x00bd138abd70e2f00903268f3db08f2d25677c9e
      --ws-interface 0.0.0.0
      --unsafe-expose
      --jsonrpc-cors all
      --no-persistent-txqueue
      --fast-unlock
      --tracing on
    ports:
      - 8545:8545
      - 8546:8546
      - 8180:8180
      - 30303:30303
    networks:
      app_net:
        ipv4_address: 172.16.0.10

  authority1:
    image: maibornwolff/eden:parity-authority1
    hostname: authority1
    container_name: authority1
    build:
      context: .
      dockerfile: ./authority.Dockerfile
      args:
        PARITY_VERSION: ${PARITY_VERSION}
        NETWORK_NAME: ${NETWORK_NAME}
        ID: 1
    volumes:
      - authority1_volume:/home/parity/.local/share/io.parity.ethereum/chains/${NETWORK_NAME}/db
    command: --config /parity/config/authority.toml
      --engine-signer 0x00aa39d30f0d20ff03a22ccfc30b7efbfca597c2
      --ws-interface 0.0.0.0
      --unsafe-expose
      --jsonrpc-cors all
      --no-persistent-txqueue
      --fast-unlock
      --tracing on
    ports:
      - 8555:8545
      - 8556:8546
      - 6180:8180
      - 40303:30303
    networks:
      app_net:
        ipv4_address: 172.16.0.11

  authority2:
    image: maibornwolff/eden:parity-authority2
    hostname: authority2
    container_name: authority2
    build:
      context: .
      dockerfile: ./authority.Dockerfile
      args:
        PARITY_VERSION: ${PARITY_VERSION}
        NETWORK_NAME: ${NETWORK_NAME}
        ID: 2
    volumes:
      - authority2_volume:/home/parity/.local/share/io.parity.ethereum/chains/${NETWORK_NAME}/db
    command: --config /parity/config/authority.toml
      --engine-signer 0x002e28950558fbede1a9675cb113f0bd20912019
      --ws-interface 0.0.0.0
      --unsafe-expose
      --jsonrpc-cors all
      --no-persistent-txqueue
      --fast-unlock
      --tracing on
    ports:
      - 8565:8545
      - 8566:8546
      - 7180:8180
      - 50303:30303
    networks:
      app_net:
        ipv4_address: 172.16.0.12

  member0:
    image: maibornwolff/eden:parity-member0
    hostname: member0
    container_name: member0
    build:
      context: .
      dockerfile: ./member.Dockerfile
      args:
        PARITY_VERSION: ${PARITY_VERSION}
        NETWORK_NAME: ${NETWORK_NAME}
    command: --config /parity/config/member.toml
      --ws-interface 0.0.0.0
      --unsafe-expose
      --jsonrpc-cors all
      --no-persistent-txqueue
      --fast-unlock
      --tracing on
    ports:
      - 8575:8545
      - 8576:8546
      - 9180:8180
    networks:
      app_net:
        ipv4_address: 172.16.0.20

  member1:
    image: maibornwolff/eden:parity-member1
    hostname: member1
    container_name: member1
    build:
      context: .
      dockerfile: ./member.Dockerfile
      args:
        PARITY_VERSION: ${PARITY_VERSION}
        NETWORK_NAME: ${NETWORK_NAME}
    command: --config /parity/config/member.toml
      --ws-interface 0.0.0.0
      --unsafe-expose
      --jsonrpc-cors all
      --no-persistent-txqueue
      --fast-unlock
      --tracing on
    ports:
      - 8585:8545
      - 8586:8546
      - 10180:8180
    networks:
      app_net:
        ipv4_address: 172.16.0.21

  member2:
    image: maibornwolff/eden:parity-member2
    hostname: member2
    container_name: member2
    build:
      context: .
      dockerfile: ./member.Dockerfile
      args:
        PARITY_VERSION: ${PARITY_VERSION}
        NETWORK_NAME: ${NETWORK_NAME}
    command: --config /parity/config/member.toml
      --ws-interface 0.0.0.0
      --unsafe-expose
      --jsonrpc-cors all
      --no-persistent-txqueue
      --fast-unlock
      --tracing on
    ports:
      - 8595:8545
      - 8596:8546
      - 20180:8180
    networks:
      app_net:
        ipv4_address: 172.16.0.22

  monitor:
    image: buythewhale/ethstats_monitor
    hostname: monitor
    container_name: monitor
    volumes:
      - ./monitor/app.json:/home/ethnetintel/eth-net-intelligence-api/app.json:ro
    networks:
      app_net:
        ipv4_address: 172.16.0.100

  dashboard:
    image: buythewhale/ethstats
    hostname: dashboard
    container_name: dashboard
    volumes:
      - ./dashboard/ws_secret.json:/eth-netstats/ws_secret.json:ro
    ports:
      - 3000:3000
    networks:
      app_net:
        ipv4_address: 172.16.0.200

  lite-explorer:
    hostname: lite-explorer
    depends_on:
      - authority0
    image: alethio/ethereum-lite-explorer
    container_name: lite-explorer
    environment:
      - APP_NODE_URL=http://localhost:8545
    ports:
      - 8800:80
    networks:
      app_net:
        ipv4_address: 172.16.0.90

volumes:
  authority0_volume:
  authority1_volume:
  authority2_volume:
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.1/24
          gateway: 172.16.0.1
