version: "3"
services:
  geth-bootnode:
    hostname: geth-bootnode
    environment:
      - nodekeyhex=08f0e1dee5c1b4645f3331a566009e41a4514b6cd28656d63d0449ecf812812b #Needs to be fix, so that the miners know the resulting enode id
    build:
      context: ./bootnode
    image: maibornwolff/eden:geth-bootnode
    ports:
      - 30301:30301/udp
    networks:
      chainnet:
        ipv4_address: 172.25.0.101 # The miners need to know the IP address later on

  geth-dev-miner-1:
    hostname: geth-dev-miner-1
    depends_on:
      - geth-bootnode
    environment:
      - address=0x8cc5a1a0802db41db826c2fcb72423744338dcb0 #derived from the private key which is passed in the args
      - bootnodeId=76a8171707eca17647a47ca99ffd348927dfa60102792ea349a25d5192e61855be83b786e376276a306afcceea4ffd1c9c77e4370b417efc39f328a0d068004c #derived from the nodekeyhex of the bootnode
      - bootnodeIp=172.25.0.101
    build:
      context: ./miner
      args:
        privatekey: df504d175ae63abf209bad9dda965310d99559620550e74521a6798a41215f46 # Please don't do something like this in production, okay?
        password: pass
    image: maibornwolff/eden:geth-dev-miner-1
    container_name: geth-miner-1
    volumes:
      - eth-data-1:/root/.ethash
    networks:
      chainnet:
        ipv4_address: 172.25.0.102 # The monitor needs to know this address

  geth-dev-miner-2:
    hostname: geth-dev-miner-2
    depends_on:
      - geth-bootnode
    environment:
      - address=0x3590aca93338b0721966a8d0c96ebf2c4c87c544 #derived from the private key which is passed in the args
      - bootnodeId=76a8171707eca17647a47ca99ffd348927dfa60102792ea349a25d5192e61855be83b786e376276a306afcceea4ffd1c9c77e4370b417efc39f328a0d068004c #derived from the nodekeyhex of the bootnode
      - bootnodeIp=172.25.0.101
    build:
      context: ./miner
      args:
        privatekey: bc5b578e0dcb2dbf98dd6e5fe62cb5a28b84a55e15fc112d4ca88e1f62bd7c35
        password: word
    image: maibornwolff/eden:geth-dev-miner-2
    container_name: geth-miner-2
    volumes:
      - eth-data-2:/root/.ethash
    networks:
      chainnet:
        ipv4_address: 172.25.0.104

  geth-dev-node:
    hostname: geth-dev-node
    depends_on:
      - geth-dev-miner-2
    environment:
      - address=0x3590aca93338b0721966a8d0c96ebf2c4c87c544 #derived from the private key which is passed in the args
      - bootnodeId=76a8171707eca17647a47ca99ffd348927dfa60102792ea349a25d5192e61855be83b786e376276a306afcceea4ffd1c9c77e4370b417efc39f328a0d068004c #derived from the nodekeyhex of the bootnode
      - bootnodeIp=172.25.0.101
    build:
      context: ./node
      args:
        privatekey: bc5b578e0dcb2dbf98dd6e5fe62cb5a28b84a55e15fc112d4ca88e1f62bd7c35
        password: word
    image: maibornwolff/eden:geth-dev-node
    container_name: geth-node
    ports:
      - 8545:8545
    healthcheck:
      test: wget http://localhost:8545
      interval: 2s
      timeout: 5s
      retries: 30
    volumes:
      - eth-data-3:/root/.ethash
    networks:
      chainnet:
        ipv4_address: 172.25.0.110

  geth-dev-swarm-1:
    hostname: geth-dev-swarm-1
    depends_on:
      - geth-dev-node
    environment:
      - address=8cc5a1a0802db41db826c2fcb72423744338dcb0 #derived from the private key which is passed in the args
      - bootnodeId=76a8171707eca17647a47ca99ffd348927dfa60102792ea349a25d5192e61855be83b786e376276a306afcceea4ffd1c9c77e4370b417efc39f328a0d068004c #derived from the nodekeyhex of the bootnode
      - bootnodeIp=172.25.0.101
    build:
      context: ./swarm
      args:
        privatekey: df504d175ae63abf209bad9dda965310d99559620550e74521a6798a41215f46
        password: pass
    image: maibornwolff/eden:geth-dev-swarm-1
    container_name: geth-swarm-1
    ports:
      - 8500:8500
      - 30399:30399/udp
    volumes:
      - eth-data-4:/root/.ethash
    networks:
      chainnet:
        ipv4_address: 172.25.0.111

  geth-dev-swarm-2:
    hostname: geth-dev-miner-3
    depends_on:
      - geth-dev-node
    environment:
      - address=3590aca93338b0721966a8d0c96ebf2c4c87c544 #derived from the private key which is passed in the args
      - bootnodeId=76a8171707eca17647a47ca99ffd348927dfa60102792ea349a25d5192e61855be83b786e376276a306afcceea4ffd1c9c77e4370b417efc39f328a0d068004c #derived from the nodekeyhex of the bootnode
      - bootnodeIp=172.25.0.101
    build:
      context: ./swarm
      args:
        privatekey: bc5b578e0dcb2dbf98dd6e5fe62cb5a28b84a55e15fc112d4ca88e1f62bd7c35
        password: pass
    image: maibornwolff/eden:geth-dev-swarm-2
    container_name: geth-swarm-2
    ports:
      - 8501:8500
      - 30340:30399/udp
    volumes:
      - eth-data-5:/root/.ethash
    networks:
      chainnet:
        ipv4_address: 172.25.0.112

  geth-explorer:
    hostname: geth-explorer
    depends_on:
      - geth-dev-node
    ports:
      - 8080:8080
    build:
      context: ./explorer
    image: maibornwolff/eden:geth-explorer
    container_name: geth-explorer
    networks:
      chainnet:
        ipv4_address: 172.25.0.125

  monitor:
    image: buythewhale/ethstats_monitor
    volumes:
      - ./monitor/app.json:/home/ethnetintel/eth-net-intelligence-api/app.json:ro
    networks:
      chainnet:
        ipv4_address: 172.25.0.135


  dashboard:
    image: buythewhale/ethstats
    volumes:
      - ./dashboard/ws_secret.json:/eth-netstats/ws_secret.json:ro
    ports:
      - 8008:3000
    networks:
      chainnet:
        ipv4_address: 172.25.0.136

networks:
  chainnet:
    driver: bridge
    ipam:
      config:
      - subnet: 172.25.0.0/24

volumes:
  eth-data-1:
  eth-data-2:
  eth-data-3:
  eth-data-4:
  eth-data-5:
  eth-data-6:
