version: '2'
services:
  geth:
    image: ethereum/client-go:v1.7.3
    command: --dev --mine --keystore "/root/.ethereum/devchain/keystore" --ws --wsaddr="0.0.0.0" --rpc --rpcaddr="0.0.0.0" --wsorigins="*" --rpccorsdomain="*" --rpcapi="db,personal,eth,net,web3,swarm,shh" --wsapi="db,personal,eth,net,web3,swarm,shh" 
    volumes:
      - ./files/password:/root/files/password:ro
      - ./files/genesis.json:/root/files/genesis.json:ro
      - ./files/keystore:/root/.ethereum/devchain/keystore:rw
    ports:
      - "30303:30303"
      - "30303:30303/udp"
      - "8545:8545"