version: "3"

services:
  bootstrap-mining:
    image: maibornwolff/eden:bootstrap-mining
    build:
      context: ./bootstrap-mining
    restart: on-failure
    container_name: bootstrap-mining
    hostname: bootstrap-mining
    entrypoint: ./start.sh
    command: '--networkid 456719 --verbosity 4 --nodekeyhex=091bd6067cb4612df85d9c1ff85cc47f259ced4d4cd99816b14f35650f59c322 --http --http.addr "0.0.0.0" --http.port 8545 --http.api "eth,web3,net,admin,debug,miner,personal" --http.corsdomain="*" --ws --ws.addr "0.0.0.0" --ws.port 8546 --ws.api "eth,web3,net,admin,debug,miner,personal" --ws.origins="*" --syncmode full --mine --miner.etherbase 0x3590aca93338b0721966a8d0c96ebf2c4c87c544 --unlock 0x3590aca93338b0721966a8d0c96ebf2c4c87c544 --password /root/.accountpassword --allow-insecure-unlock'
    ports:
      - 30303:30303
      - 30303:30303/udp
      - 8545:8545
      - 8546:8546
    healthcheck:
      test: wget http://localhost:8545
      interval: 2s
      timeout: 5s
      retries: 30

  geth-node:
    image: maibornwolff/eden:geth-node
    build:
      context: ./geth-node
    restart: on-failure
    depends_on:
      - bootstrap-mining
    entrypoint: ./start.sh
    command: '--networkid 456719 --verbosity 4 --bootnodes "enode://288b97262895b1c7ec61cf314c2e2004407d0a5dc77566877aad1f2a36659c8b698f4b56fd06c4a0c0bf007b4cfb3e7122d907da3b005fa90e724441902eb19e@XXX:30303" --http --http.corsdomain="*" --syncmode full'

  lite-explorer:
    hostname: lite-explorer
    depends_on:
      - bootstrap-mining
    image: alethio/ethereum-lite-explorer
    container_name: lite-explorer
    environment:
      - APP_NODE_URL=http://localhost:8545
    ports:
      - 8800:80

  monitor:
    hostname: monitor
    depends_on:
      - bootstrap-mining
    image: buythewhale/ethstats_monitor
    container_name: monitor
    volumes:
      - ./monitor/app.json:/home/ethnetintel/eth-net-intelligence-api/app.json:ro

  dashboard:
    hostname: dashboard
    depends_on:
      - bootstrap-mining
      - monitor
    image: buythewhale/ethstats
    container_name: dashboard
    volumes:
      - ./dashboard/ws_secret.json:/eth-netstats/ws_secret.json:ro
    ports:
      - 8008:3000
