version: "3.2"
services:
  geth_mining:
    build:
      context: monitored-geth-client
      cache_from:
        - maibornwolff/eden:geth_mining
    image: maibornwolff/eden:geth_mining
    restart: on-failure
    container_name: geth_mining
    entrypoint: /root/start.sh
    command: '--datadir=~/.ethereum/devchain --nodekeyhex=091bd6067cb4612df85d9c1ff85cc47f259ced4d4cd99816b14f35650f59c322 --rpcapi "db,personal,eth,net,web3,swarm" --rpccorsdomain="*" --rpcvhosts="*" --networkid=456719 --rpc --rpcaddr="0.0.0.0" --mine'
    volumes:
      - ./files/password:/root/files/password:ro
      - ./files/genesis.json:/root/files/genesis.json:ro
      - ./files/keystore:/root/.ethereum/devchain/keystore:rw

      # cannot use localtime atm, open docker issue: https://github.com/docker/for-mac/issues/2396
      #- /etc/localtime:/etc/localtime:ro

      # ensutils are available on geth_mining
      - ./files/ensutils.js:/root/files/ensutils.js:ro
    ports:
      - "30303:30303"
      - "30303:30303/udp"
      - "8545:8545"

  geth:
    build:
      context: monitored-geth-client
      cache_from:
        - maibornwolff/eden:geth
    image: maibornwolff/eden:geth
    restart: on-failure
    container_name: geth
    entrypoint: /root/start.sh
    volumes:
      - ./files/password:/root/files/password:ro
      - ./files/genesis.json:/root/files/genesis.json:ro
      - ./files/keystore:/root/.ethereum/devchain/keystore:rw
    command: '--datadir=~/.ethereum/devchain --rpccorsdomain="*" --networkid=456719 --rpc --bootnodes="enode://288b97262895b1c7ec61cf314c2e2004407d0a5dc77566877aad1f2a36659c8b698f4b56fd06c4a0c0bf007b4cfb3e7122d907da3b005fa90e724441902eb19e@127.0.0.1:30303"'

  monitor:
    image: buythewhale/ethstats_monitor
    volumes:
      - ./monitored-geth-client/app.json:/home/ethnetintel/eth-net-intelligence-api/app.json:ro

  dashboard:
    image: buythewhale/ethstats
    volumes:
      - ./monitored-geth-client/ws_secret.json:/eth-netstats/ws_secret.json:ro
    ports:
      - "3000:3000"

  explorer:
    build:
      context: explorer
      cache_from:
        - maibornwolff/eden:explorer
    image: maibornwolff/eden:explorer
    restart: always
    ports:
      - 3002:3000
