version: '3'
services:
  tools:
    build: .                # dockerfile is in this dir
    container_name: tools
    stdin_open: true        # equivalent to docker run -i
    tty: true               # equivalent to docker run -t
    entrypoint: /bin/bash   # process of our container is the terminal itself
    working_dir: /
    volumes:
      - ./volume:/root/volume
      - ./volume/contracts:/oyente/oyente/contracts
      # insert folder with your projects contracts here
    ports:
      - "8546:8545"
      # avoid interference with ethereum-docker
