name: Release

on:
  push:
    branches:
      - master

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: http://registry.npmjs.org/

      - name: Install dependencies
        run: npm ci

      - name: Log into GitHub container registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build images
        run: npm run build

      - name: Push images
        run: npm run deploy
